language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run test:coverage
cache:
  directories:
    - node_modules

before_install:
  - npm install codecov.io coveralls
  - npm install -g npm@5 # skip this if you are using node 9
  - npm install -g greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js